version: '3.8'

services:
  check_txt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./temp:/app/temp:rw
      - ./static:/app/static:ro
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8090
      - MAX_FILE_SIZE=100
      - DEEP_SCAN=true
      - VIRUS_SCAN=true
      - RUST_LOG=info
    restart: unless-stopped
    # Add resource limits to prevent memory issues
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Ensure proper permissions for mounted volumes
    user: "1000:1000" 